//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRCToolBox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRCToolBox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Unity Projects.
        /// </summary>
        public static string BackupUnityProjects {
            get {
                return ResourceManager.GetString("BackupUnityProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the currently displayed photo to the candidate list..
        /// </summary>
        public static string CandiAddToolTip {
            get {
                return ResourceManager.GetString("CandiAddToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to the list.
        /// </summary>
        public static string CandidateAdd {
            get {
                return ResourceManager.GetString("CandidateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all.
        /// </summary>
        public static string CandidateList {
            get {
                return ResourceManager.GetString("CandidateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all photos from the candidate list..
        /// </summary>
        public static string CandiToolTip {
            get {
                return ResourceManager.GetString("CandiToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can copy the avatar name..
        /// </summary>
        public static string CopyAvatar {
            get {
                return ResourceManager.GetString("CopyAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can copy the post..
        /// </summary>
        public static string CopyPost {
            get {
                return ResourceManager.GetString("CopyPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can copy the creator&apos;s name..
        /// </summary>
        public static string CopyProducer {
            get {
                return ResourceManager.GetString("CopyProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can copy the creator&apos;s name..
        /// </summary>
        public static string CopyProducer2 {
            get {
                return ResourceManager.GetString("CopyProducer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can copy the world name..
        /// </summary>
        public static string CopyWorld {
            get {
                return ResourceManager.GetString("CopyWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string JoinNotification {
            get {
                return ResourceManager.GetString("JoinNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Search.
        /// </summary>
        public static string LogSearch {
            get {
                return ResourceManager.GetString("LogSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark it as posted..
        /// </summary>
        public static string MarkPost {
            get {
                return ResourceManager.GetString("MarkPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Logs.
        /// </summary>
        public static string MoveLogs {
            get {
                return ResourceManager.GetString("MoveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Photos.
        /// </summary>
        public static string MovePhotos {
            get {
                return ResourceManager.GetString("MovePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple selection.
        /// </summary>
        public static string MultipleSelect {
            get {
                return ResourceManager.GetString("MultipleSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Content.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your post content....
        /// </summary>
        public static string PostContentPl {
            get {
                return ResourceManager.GetString("PostContentPl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted.
        /// </summary>
        public static string Posted {
            get {
                return ResourceManager.GetString("Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        public static string Producer {
            get {
                return ResourceManager.GetString("Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        public static string Producer2 {
            get {
                return ResourceManager.GetString("Producer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save photo information.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the photo information will be saved..
        /// </summary>
        public static string SaveButtonTooltip {
            get {
                return ResourceManager.GetString("SaveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all photo information and posts..
        /// </summary>
        public static string SavePhotoAndPostConent {
            get {
                return ResourceManager.GetString("SavePhotoAndPostConent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search conditions.
        /// </summary>
        public static string SearchConditions {
            get {
                return ResourceManager.GetString("SearchConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the photo tag…….
        /// </summary>
        public static string TagPlaceHolder {
            get {
                return ResourceManager.GetString("TagPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity.
        /// </summary>
        public static string Unity {
            get {
                return ResourceManager.GetString("Unity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Update is available.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
    }
}
